# Shards, gradients, optimizer states, but keeps the full model in memory on each GPU
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
#  gradient_accumulation_steps: "auto"  # Default Value
#  gradient_clipping: 1.0  # Default Value
  offload_optimizer_device: None
  offload_param_device: None
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
# machine_rank: 0
# main_process_ip: null
# main_process_port: null
main_training_function: main
mixed_precision: 'bf16'
# rdzv_backend: static
same_network: true
# num_machines: 1
# num_processes: 4
use_cpu: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false